[book]
authors = ["David Hedgren"]
language = "sv"
multilingual = false
src = "src"
title = "Data 101"

[rust]
edition = "2018"

[preprocessor.index]

[preprocessor.links]

[output.html]
#additional-css = ["gruvbox.css"]

[output.html.search]
limit-results = 10

[preprocessor.variables]
command = "./expand-variables/target/release/expand-variables"

[variables]
CURRENT_UBS = "[Hadi Zarshamfar](mailto:hadi.zarshamfar@chalmers.se)"
CURRENT_SYV = "[Ingegerd Nilsson](mailto:ingegerd.nilsson@chalmers.se)"
CURRENT_PA = "[Magnus Almgren](mailto:magnus.almgren@chalmers.se)"